### ISSUE TITLE
建议确定一下模块的作用域

### ISSUE THREAD

**Issue by bigQY** [HuanCheng65/MIUILevelChecker#3]
对于LSPosed和edxposed白名单模式的用户来说，确定作用域比较重要，建议大佬可以排查一下作用域。现在这样直接把miui和xiaomi相关的app全部hook的话逐个加入白名单太麻烦了。

建议在软件的关于界面添加对作用域的说明，方便用户设置

**Comment by HuanCheng65** [comment]
已加入
